### ISSUE TITLE
divvier -partial removing entire columns

### ISSUE THREAD

**Issue by mscharmann** [simonwhelan/fastZorro#1]
Hello,
I recently discovered Divvier through a link from PREQUAL and I'm currently experimenting with using the two of them in combination to make sense of homolog genes from transcriptomes. First of all: awesome tools! --- I want to run Divvier on the AA MSA and then back-translate to CDS (using the corresponding CDS MSA) , but it seems I can't do that as Divvier -partial does drop some columns entirely. Is this expected behaviour? Alternatively, I thought parsing the .PP file to extract which columns were dropped / retained, but I'm not sure how they can be identified from the .PP file. Many thanks, Mathias

**Comment by simonwhelan** [comment]
Hi mscharmann!

Divvier examines each column in an MSA in turn and groups together the characters by a measure of their evidence for shared homology. So imagine a column ABCDEF that ends up with the homology clusters: {ABC},{D,E},{F}. Divvier has two main settings: divvying and partial filtering. Partial filtering only returns the largest homology cluster, in this case {ABC}, and is 'lossy', in the sense that it loses some clusters, so {D,E}, and {F} are discarded. In contrast divvying keeps all clusters and gives each its own column, so the columns will be ABC***, ***DE*, and *****F. The '*' characters are there as a placeholder so you can reconstitute the column or can be replaced with gaps and input into a standard phylogeny program. So the direct answer to your question use Divvying and then extract as you wish.

I hope that answers you question!

Simon

**Comment by simonwhelan** [comment]
Closing this issue. Let me know if there are ongoing problems
