### ISSUE TITLE
Segmentation fault calculating posterior probabilities

### ISSUE THREAD

**Issue by aaronmussig** [simonwhelan/fastZorro#4]
Hello,

I'm running into an issue where the 20th pairwise posterior calculation throws a segfault regardless of input options (unless approx is changed where it throws on a different pair). I'm wondering if there are any limitations given the input or if there are any bad data on my end? Attached are my [input](https://github.com/simonwhelan/Divvier/files/3347629/ar122_TIGR00490.zip) and [output](https://github.com/simonwhelan/Divvier/files/3347637/output.txt).

Thanks,
Aaron

**Comment by simonwhelan** [comment]
Hi Aaron,

Thanks for getting touch. I've been looking into the bug, but I'm struggling to replicate it. I'm testing it on a MacOS Mojave 10.14.4 and the posterior probabilities complete on at least two of the test cases you provided. What system are you running on? 

I've had a look at the data to try and see what the problem might be. There are several sequences where there are only gaps, which might cause problems for Divvier and I'd try removing them and see if that solves the problem. 

/Simon

**Comment by aaronmussig** [comment]
Thanks for the response. I compiled Divvier on both Ubuntu 12.04.5 LTS (Intel Xeon E5-2650, and an AMD Opteron 6174) and Centos 7 (Intel Xeon Gold 5117) with the same issue. Removing the sequences which contained only gaps resolved the issue. Interestingly, removing only ~20 of the fully gapped sequences was sufficient.

I'd say this is just a user error, the program works fine without fully gapped sequences.

Thanks,
Aaron
