### ISSUE TITLE
Release and version tag for Bioconda

### ISSUE THREAD

**Issue by emilhaegglund** [simonwhelan/fastZorro#7]
Hi!
I was going to add Divvier to bioconda, but they require a link to a stable release. Do you think you could add a release and a version tag to Divvier?

Cheers

**Comment by simonwhelan** [comment]
Hi,

I've added a (manual for now) version tag to Divvier and put it as a release. Let me know if you need anything further!

 /Simon

**Comment by emilhaegglund** [comment]
Thanks, now it's possible to install divvier with Bioconda. You could also add a badge to the readme to let people know of this possibility.
https://anaconda.org/bioconda/divvier/badges

/Emil

**Comment by simonwhelan** [comment]
Realised this hadn't been closed. Closed now and thanks!
